# validate any chart changes under charts directory
name: Operator Chart
env:
  HELM_VERSION: v3.17.3
  KUSTOMIZE_VERSION: 5.6.0
on:
  push:
    # Exclude branches created by Dependabot to avoid triggering current workflow
    # for PRs initiated by Dependabot.
    branches-ignore:
      - 'dependabot/**'
  pull_request:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test-on-kubernetes-matrix:
    name: Test Operator Chart on Kubernetes
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Here support the latest three minor releases of Kubernetes, this can be considered to be roughly
        # the same as the End of Life of the Kubernetes release: https://kubernetes.io/releases/
        # Please remember to update the CI Schedule Workflow when we add a new version.
        k8s: [ v1.31.0, v1.32.0, v1.33.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up Kustomize
        uses: syntaqx/setup-kustomize@v1
        with:
          kustomize-version: ${{ env.KUSTOMIZE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run chart-testing (template)
        run: |
          cat <<EOF > post-render.sh
          #!/bin/sh
          # save helm stdout to file, kustomize will read this
          cat > all.yaml
          kustomize build
          EOF

          chmod +x post-render.sh

          cat <<EOF > kustomization.yaml
          resources:
            - all.yaml
          EOF

          helm template --set operator.replicaCount=2 --dependency-update ./charts/karmada-operator \
            --post-renderer ./post-render.sh --debug > /dev/null

          rm post-render.sh all.yaml kustomization.yaml

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.9
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$( ct list-changed --chart-dirs ./charts/karmada-operator --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs ./charts/karmada-operator --debug --check-version-increment=false --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (install)
        run: |
          export CLUSTER_VERSION=kindest/node:${{ matrix.k8s }}
          hack/setup-dev-base.sh
          export KUBECONFIG=~/.kube/karmada.config
          
          
          helm install karmada-operator --namespace karmada-system --create-namespace --dependency-update charts/karmada-operator --debug --set operator.replicaCount=2 --timeout 800s
          kubectl get deployment --namespace karmada-system karmada-operator
          kubectl get deployment --namespace karmada-system karmada-operator -o jsonpath='{.spec.replicas}' | grep 2

      - name: Run chart-testing (upgrade)
        run: |
          # edit operator replicas to test the upgrade.
          export KUBECONFIG=~/.kube/karmada.config
          helm upgrade karmada-operator --namespace karmada-system --create-namespace --dependency-update charts/karmada-operator --debug --set operator.replicaCount=1 --timeout 800s
          kubectl get deployment --namespace karmada-system karmada-operator
          kubectl get deployment --namespace karmada-system karmada-operator -o jsonpath='{.spec.replicas}' | grep 1
          
